name: tablah
description: Desarrollo de Ingeniería. Clínica de Tecnología Asistiva, FLENI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_tts: ^3.6.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  text_to_speech: ^0.2.3
  url_launcher: ^6.2.5

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
